name = "teamGF Official Modpack"
author = "Sannity"
version = "3.0.3"
description = "Modpack of the teamGF Gaming Community, Feel free to stop into our Server!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ad053f154d5e3dc3041df5b4a7b8701eb75601b606280a572f7142e8b59209b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"
