name = "teamGF Official Modpack"
author = "Sannity"
version = "3.0.4"
description = "Modpack of the teamGF Gaming Community, Feel free to stop into our Server!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3785a95e1e7443e97f532617bf84324acce7e79e61a918e9a6564c8232c65ecf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"
