name = "teamGF Official Modpack"
author = "Sannity"
version = "3.0.5"
description = "Modpack of the teamGF Gaming Community, Feel free to stop into our Server!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "187d093c1ba1ee1bc0386f763eacc319286e70e145be35f2930cd18205d19144"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"
