name: Modpack Release | Pipeline

on:
  push:
    branches:
      - main

env:
  MODPACK_PATH: 'main'
  default-release-modrinth: 'false'
  default-release-curseforge: 'true'


jobs:
  release-please:
    name: Handle Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write


    steps:      
      - name: Perform Release with Release Please
        id: release-please
        uses: googleapis/release-please-action@v4
        
      - name: Check Out Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        if: ${{ steps.release-please.outputs.releases_created == 'true' }}

      - name: Parse Pack File
        id: parse
        uses: ./.github/actions/parse
        with:
          modpack: ${{ env.MODPACK_PATH }}
        if: ${{ steps.release-please.outputs.releases_created == 'true' }}

      - name: Set Mod Vendors
        id: set-mod-vendors
        run: |
          [[ ! -z "${{ secrets.CURSEFORGE_TOKEN }}" && ! -z "${{ secrets.CURSEFORGE_ID }}" ]] && echo "curseforge=true" >> $GITHUB_OUTPUT || echo "curseforge=false" >> $GITHUB_OUTPUT
          [[ ! -z "${{ secrets.MODRINTH_TOKEN }}" && ! -z "${{ secrets.MODRINTH_ID }}" ]] && echo "modrinth=true" >> $GITHUB_OUTPUT || echo "modrinth=false" >> $GITHUB_OUTPUT
        shell: bash
        if: ${{ steps.release-please.outputs.releases_created == 'true' }}

      - name: Build Modpack
        uses: ./.github/actions/build
        with:
          modpack: ${{ env.MODPACK_PATH }}
          release-tag: ${{ steps.release-please.outputs['main--tag_name'] }}
          build-modrinth: ${{ env.default-release-modrinth }}
          build-curse: ${{ env.default-release-curseforge }}
        if: ${{ steps.release-please.outputs.releases_created == 'true' }}

      # --- Release
      - name: Release Modpack to Vendors
        uses: ./.github/actions/release
        with:
          modpack: ${{ env.MODPACK_PATH }}
          release-tag: ${{ steps.release-please.outputs['main--tag_name'] }}
          loader: ${{ steps.parse.outputs.loader }}
          game-version: ${{ steps.parse.outputs.game-version }}
          upload-modrinth: ${{ steps.set-mod-vendors.outputs.modrinth }}
          upload-curse: ${{ steps.set-mod-vendors.outputs.curseforge }}
          MODRINTH_ID: ${{ secrets.MODRINTH_ID }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_ID: ${{ secrets.CURSEFORGE_ID }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        if: |
          steps.release-please.outputs.releases_created == 'true' &&
          (steps.set-mod-vendors.outputs.modrinth || steps.set-mod-vendors.outputs.curseforge)
